# Generated by Django 5.2.5 on 2025-09-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('revenue_ttm', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('same_store_sales', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
