# Generated by Django 5.2.5 on 2025-09-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='recommendation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='season',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=10, null=True),
        ),
    ]
