# Generated by Django 5.2.5 on 2025-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
