# Generated by Django 5.2.5 on 2025-09-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_alter_stock_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
